# ***Numpy tutorial***

In [179]:
import numpy as np


In [180]:
j_arr = np.array([[3,6,32,7]])

In [181]:
j_arr

array([[ 3,  6, 32,  7]])

In [182]:
j_arr[0,3]

7

In [183]:
j_arr.dtype

dtype('int64')

In [184]:
j_arr[0,3] = 20

In [185]:
j_arr[0,3]

20

# **1,Conversion from other Python structures (e.g., lists, tuples)**

In [186]:
m_arr = np.array([[1,2,3],[23,34,45],[345,456,567]])

In [187]:
m_arr

array([[  1,   2,   3],
       [ 23,  34,  45],
       [345, 456, 567]])

In [188]:
m_arr.shape

(3, 3)

In [189]:
m_arr.size

9

In [190]:
n_arr = np.array({2,3,4,5,5,})

In [191]:
n_arr

array({2, 3, 4, 5}, dtype=object)

# ***2,Intrinsic numpy  array creation objects (e.g., arange, ones, zeros, etc.)***

In [192]:
o_arr = np.zeros((3,3))

In [193]:
o_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [194]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
l_space = np.linspace(1,10,5)

In [196]:
l_space

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [197]:
emp = np.empty((3,3))

In [198]:
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [199]:
ide = np.identity(4)

In [200]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [201]:
ide = ide.reshape(2,8)

In [202]:
ide

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [203]:
ide = ide.ravel()

In [204]:
ide

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

# ***Axis***

In [205]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [206]:
ar = np.array(x)

In [207]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [208]:
ar.sum(axis=0)

array([12, 15, 18])

In [209]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [210]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [211]:
ar.flat

In [212]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [213]:
ar.ndim

2

In [214]:
ar.size

9

In [215]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [216]:
ar.argmax()

8

In [217]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [218]:
ar.argmax(axis=0)

array([2, 2, 2])

In [219]:
ar.argmin(axis=1)

array([0, 0, 0])

In [220]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [221]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [222]:
aq = np.array([[3,5,7],[1,2,6],[7,5,9]])

In [223]:
aq + ar

array([[ 4,  7, 10],
       [ 5,  7, 12],
       [14, 13, 18]])

In [224]:
aq * ar

array([[ 3, 10, 21],
       [ 4, 10, 36],
       [49, 40, 81]])